.github/workflows/main.yml, Makefile, README.md
In this PR we are uploading the code coverage to codecov inside github actions.
=> Upload code coverage to codecov

CHANGELOG.md, management/actions.go, management/client.go, management/client_test.go, management/email.go, management/management.gen.go, management/management.go, management/management_test.go, management/tenant.go
As we are preparing for v0.5.0 in this PR we take advantage of our first release to remove inherited deprecations across the project. We're listing them as well in the changelog together with the breaking changes introduced after fixing the linting errors.
=> Add Changelog for v0.5.0 and remove deprecations

management/user.go
Clarify intended usage of roles in app metadata vs RBAC.
See: https://github.com/go-auth0/auth0/pull/254
No tests run. Documentation change only.
=> Clarify intended usage of roles in app metadata vs RBAC.

CHANGELOG.md
=> Update changelog for v0.6.0

CHANGELOG.md
=> Add changelog for v0.6.1

management/management.go, management/management_test.go
Go's url.PathEscape will not escape "/", but some user IDs do have a valid "/" in them.
See https://github.com/golang/go/blob/b55a2fb3b0d67b346bac871737b862f16e5a6447/src/net/url/url.go#L141.
This PR fixes such cases.
=> ESD-16399: Ensure paths are escaped correctly when constructing URI

CHANGELOG.md
=> Add changelog for v0.6.3

management/guardian.go, management/guardian_test.go
Fixes #46 
Corrects the uri path for webauthn-platform mfa enable func.
=> #46: Fix uri path for webauthn-platform mfa

management/actions_test.go
Refactor actions tests so they can be ran in any order and they clean up the test tenant after running.
=> [DXCDT-110] [DXCDT-113] Refactor actions tests

management/anomaly_test.go, management/attack_protection_test.go, management/blacklist_test.go, management/branding_test.go, management/custom_domain_test.go
Refactor anomaly, attack protection, blacklist, custom domain, branding tests so they can be ran in any order and they clean up the test tenant after running.
=> [DXCDT-110] [DXCDT-113] Refactor anomaly, attack protection, blacklist, custom domain, branding tests

management/actions_test.go, management/grant_test.go, management/guardian_test.go, management/user_test.go
Refactor grant, guardian tests so they can be ran in any order and they clean up the test tenant after running.
=> [DXCDT-110] [DXCDT-113] Refactor grant, guardian tests

management/resource_server_test.go, management/role_test.go, management/user_test.go
Refactor user, role tests so they can be ran in any order and they clean up the test tenant after running.
=> [DXCDT-110] [DXCDT-113] Refactor user, role tests

management/rule_test.go, management/stat_test.go, management/tenant_test.go, management/ticket_test.go, management/user_test.go
Refactor rule, stat, ticket, tenant tests so they can be ran in any order and they clean up the test tenant after running.
=> [DXCDT-110] [DXCDT-113] Refactor rule, stat, ticket, tenant tests

management/hook_test.go, management/job_test.go, management/prompt_test.go, management/signing_key_test.go
Refactor signing key, prompt, hook, job tests so they can be ran in any order and they clean up the test tenant after running.
=> [DXCDT-110] [DXCDT-113] Refactor signing key, prompt, hook, job tests

management/log_stream_test.go, management/log_test.go
Refactor log, log_stream tests so they can be ran in any order and they clean up the test tenant after running.
=> [DXCDT-110] [DXCDT-113] Refactor log, log_stream tests

management/rule_config_test.go
Refactor rule config tests so they can be ran in any order and they clean up the test tenant after running.
=> [DXCDT-110] [DXCDT-113] Refactor rule config tests

.github/workflows/e2e-tests.yml, .github/workflows/main.yml
Updating the CI config to run the tests with go-vcr for all PRs and main and to have another manual workflow to run tests against the real tenant.
=> DXCDT-130 Update ci to run tests with vcr recordings

.github/workflows/e2e-tests.yml, .github/workflows/main.yml, go.mod
=> Bump go version to 1.18

CHANGELOG.md
=> Add change log for v0.6.4

management/guardian.go, management/guardian_test.go, management/management.gen.go, management/management.gen_test.go, management/testdata/recordings/TestGuardian/MultiFactor/WebAuthn_Platform/Enable.yaml, management/testdata/recordings/TestGuardian/MultiFactor/WebAuthn_Platform/Settings.yaml, management/testdata/recordings/TestGuardian/MultiFactor/WebAuthn_Roaming/Enable.yaml, management/testdata/recordings/TestGuardian/MultiFactor/WebAuthn_Roaming/Settings.yaml
This PR adds support to update settings on WebAuthn Platform and Roaming, needed for https://github.com/auth0/terraform-provider-auth0/issues/165.
=> [DXCDT-175] Add read and update to WebAuthn Platform and Roaming Settings

management/guardian.go, management/guardian_test.go, management/management.gen.go, management/management.gen_test.go, management/testdata/recordings/TestGuardian/MultiFactor/Push/CustomApp.yaml
This PR adds support to update custom app settings on push mfa, needed for https://github.com/auth0/terraform-provider-auth0/issues/165.
=> [DXCDT-175] Add read and update to Push CustomApp Settings

management/guardian.go, management/guardian_test.go, management/management.gen.go, management/management.gen_test.go, management/testdata/recordings/TestGuardian/MultiFactor/Recovery_Code_Enable.yaml
This PR adds support to update custom app settings on push mfa, needed for https://github.com/auth0/terraform-provider-auth0/issues/165.
=> [DXCDT-175] Add enable recovery code mfa

CHANGELOG.md
=> Add Changelog for v0.8.0

management/connection.go, management/connection_test.go
Fixes: https://github.com/auth0/go-auth0/issues/18.
=> [DXCDT-174] Add upstream_params to connection options

CHANGELOG.md
Updating changelog for upcoming 0.9.0 release.
=> Updating changelog 0.9.0

CHANGELOG.md
=> Add Changelog for v0.9.1

management/management.gen.go, management/management.gen_test.go, management/user.go
This PR aims to close this [issue](https://github.com/auth0/go-auth0/issues/77).
=> `Multifactor` field added to `User` struct

management/management.gen.go, management/management.gen_test.go, management/user.go
This PR aims to close this https://github.com/auth0/go-auth0/issues/16.
=> `ClientID` field added to `User` struct

CHANGELOG.md
=> Add Changelog for v0.9.3

management/testdata/recordings/TestBrandingThemeManager_Create.yaml, management/testdata/recordings/TestBrandingThemeManager_Delete.yaml, management/testdata/recordings/TestBrandingThemeManager_Read.yaml, management/testdata/recordings/TestBrandingThemeManager_Update.yaml
In this PR we are adding recordings for branding themes tests.
=> [1/2] [DXCDT-198] Add recordings for branding themes tests

management/branding_theme.go, management/branding_theme_test.go, management/management.gen.go, management/management.gen_test.go, management/management.go, management/testdata/recordings/TestBrandingThemeManager_Create.yaml, management/testdata/recordings/TestBrandingThemeManager_Delete.yaml, management/testdata/recordings/TestBrandingThemeManager_Read.yaml, management/testdata/recordings/TestBrandingThemeManager_Update.yaml
In this PR we are adding support for branding themes.
=> [2/2] [DXCDT-198] Add support for branding themes

management/management.go, management/management_error.go, management/management_option.go, management/management_request.go
No code was harmed during this process.
=> Split management.go in multiple files

CHANGELOG.md
=> Add changelog for v0.10.1

CHANGELOG.md
Updating changelog for 0.11.0. This release requires more explanation than others provided the large set or breaking changes included.
- Original PR: https://github.com/auth0/go-auth0/pull/113
=> Updating changelog for 0.11.0

CHANGELOG.md
=> Add changelog for v0.12.0

CHANGELOG.md
=> Add changelog for v0.13.0

.github/workflows/e2e-tests.yml, .github/workflows/main.yml, Makefile
=> Add ci step to check for go vulnerabilities

management/job.go
As pointed out in https://github.com/auth0/go-auth0/issues/134, the `job.ImportUsers()` func is currently broken as it tries to re-encode a multi part form data that has already been encoded. This regression was unfortunately introduced through: https://github.com/auth0/go-auth0/pull/108/files#diff-fa5a969e71bf52ff49ea8e0a125ddd8355c7dea9e6efe93a82d927a41ea12119L129-L153. 
In this PR we're aiming at reverting the change and leaving the code a bit tidier.
=> Fix import users job

management/job.go, management/job_test.go, management/management.gen.go, management/management.gen_test.go, management/testdata/recordings/TestJobManager_ImportUsers.yaml
When a job completes the job status response will include totals of successful, failed, inserted, and updated records (https://auth0.com/docs/manage-users/user-migration/bulk-user-imports#check-job-status). 
The goal of this PR is to provide the summary on the jobs when reading a job’s details through https://auth0.com/docs/api/management/v2#!/Jobs/get_jobs_by_id.
=> DXCDT-309: Add summary to job

management/job.go, management/job_test.go, management/management.gen.go, management/management.gen_test.go, management/testdata/recordings/TestJobManager_ReadErrors.yaml
We are enhancing the job manager capabilities by introducing a func to retrieve Job errors (https://auth0.com/docs/api/management/v2#!/Jobs/get_errors).
=> Add ability to retrieve job errors

CHANGELOG.md
=> Add changelog for v0.14.0

README.md
Improved some links to documentation.
- http://docs.auth0.com/ is now redirect to http://auth0.com, but http://auth0.com/docs is better
- pkg.go.dev link is [old version of this sdk](https://github.com/go-auth0/auth0). I think current version is `https://pkg.go.dev/github.com/auth0/go-auth0`.
=> Improved links to documentation.

management/attack_protection.go, management/attack_protection_test.go, management/management.gen.go, management/management.gen_test.go, management/testdata/recordings/TestAttackProtection/Get_breached_password_detection_settings.yaml, management/testdata/recordings/TestAttackProtection/Update_breached_password_detection_settings.yaml
This PR aims to contribute to the closure of https://github.com/auth0/terraform-provider-auth0/issues/386.
=> Add `Stage` field to `BreachedPasswordDetection` struct

CHANGELOG.md
=> Add changelog for v0.15.0

CHANGELOG.md
=> Add changelog for v0.15.1

.github/workflows/main.yml, .golangci.yml, Makefile
=> Update golangci-lint config

README.md
Adds the header banner for go-auth0 to the top of the readme
=> Add header banner to readme

CHANGELOG.md, README.md
Adds the changelog for the upcoming v0.16.0 release
=> Add v0.16.0 changelog

management/management.gen.go, management/management.gen_test.go, management/tenant.go
Adds the `mfa_show_factor_list_on_enrollment` tenant flag to the list of supported tenant flags
#186
Tested locally that setting `MFAShowFactorListOnEnrollment` in true/false toggles the option in the UI
=> Support mfa_show_factor_list_on_enrollment tenant flag

management/management.gen.go, management/management.gen_test.go, management/ticket.go
Exposes the `organization_id` property on a `Ticket`
#192
=> Support organization_id on Ticket

CHANGELOG.md
Adds the changelog entry for `v0.17.0`.
This is still done manually, I attempted to use ship but because of how the release process has worked in go-auth0 (the tag is not associated with `main`) there are issues with determining the PRs to include. I will look to see how we can improve this in future
=> Add changelog for v0.17.0

CHANGELOG.md
Adds the changelog entry for v0.17.1
=> Add changelog entry for v0.17.1

management/client.go, management/client_test.go, test/data/recordings/TestClient_UpdateCredential.yaml
Add ability to update a credential's expires_at property.
=> SDK-4145: Add ability to update a credential's expires_at property

MIGRATION_GUIDE.md, authentication/oauth.go, management/organization.go, management/organization_test.go, management/resource_server.go
This PR removes a couple of functions (renaming one) and updates the doc string for LoginWithPassword as discussed at https://github.com/auth0/go-auth0/pull/222#discussion_r1228142330.
One function removal is for consistency (it used the singular form rather than plural) and the other because it's the only function that provided full pagination in the SDK, and has been removed in case we want to investigate adding this to all APIs in future.
=> Rename/remove some functions, update LoginWithPassword doc string

CHANGELOG.md
This PR updates the Changelog for the beta release.
=> Add v1.0.0-beta.0 changelog

README.md
I corrected the link to the LICENSE file in README.md because it was incorrect.
=> fix link to license file in README.md

management/management.gen.go, management/management.gen_test.go, management/tenant.go, management/tenant_test.go, test/data/recordings/TestTenantManager.yaml
This PR adds support for `OIDCLogoutPromptEnabled` within the Tenant struct.
- https://github.com/auth0/terraform-provider-auth0/issues/701
- https://github.com/auth0/terraform-provider-auth0/pull/754
=> SDK-4421: Add support for OIDCLogoutPrompt toggle for Tenant

CHANGELOG.md
Adds the changelog entry for the v1.0.0 GA release
=> Add v1.0.0 changelog entry

management/connection.go, management/management.gen.go, management/management.gen_test.go
This PR adds all known properties to the `ad`, `adfs,` `pingfederate`, `saml`,  and `waad` connection options to prevent these options being removed when a update is performed
- [] All new/changed/fixed functionality is covered by tests (or N/A)
- [] I have added documentation for all new/changed functionality (or N/A)
=> [SDK-4483] Add all known options to ad, adfs, pingfederate, saml, and waad

CHANGELOG.md
Adds the changelog entry for the v1.0.1 release
=> Add v1.0.1 changelog entry

CHANGELOG.md
Adds the changelog entry for v1.0.2
=> Add v1.0.2 changelog entry

.github/workflows/e2e-tests.yml, .github/workflows/govulncheck.yml, .github/workflows/main.yml, .github/workflows/semgrep.yml, go.mod
Following Go's release policy, https://go.dev/doc/devel/release#policy, we're updating the go version to 1.20 so we can also get some security fixes out of the box as 1.19 is no longer supported.
=> Bump go to 1.20 and update gh actions

management/management.gen.go, management/management.gen_test.go, management/tenant.go
Moves `allow_organization_name_in_authentication_api` to the top level settings as this was incorrectly placed under flags
=> Move AllowOrgNameInAuthAPI to top level settings

CHANGELOG.md, README.md
Adds the changelog entry for v1.1.0
=> Add v1.1.0 changelog entry

.github/workflows/govulncheck.yml
As `pull_request_target` by default runs against the base branch, we want to checkout the repo ourself to ensure we're running against the code changes in a PR.
I don't think this will run against the PR for similar reasons
=> Checkout correct ref on vulncheck

management/client.go
- removes reference to a rollout flag that has since been enabled everywhere
=> fix: remove misleading comment

management/management.gen.go, management/management.gen_test.go, management/tenant.go
This should be a tenant setting not a flag
=> Move CustomizeMFAInPostLoginAction to top level tenant settings

.github/dependabot.yml, .github/workflows/semgrep.yml
This PR updates our GitHub CI workflows for the repository. It updates the Semgrep workflow to follow our other repositories' approaches. It also adds a Dependabot configuration for keeping Actions up to date.
N/A
This updates our continuous integration tests.
=> chore: Update GitHub CI workflows

.github/ISSUE_TEMPLATE/report_a_bug.yml
Link to the community homepage as we do in other SDK repos
=> Fix community link in report a bug template

auth0_test.go, management/branding_test.go, management/client_test.go, management/log_test.go, management/management_error_test.go, management/management_test.go, management/tenant_test.go, management/user_test.go, test/data/recordings/TestLogManager_Search.yaml, test/data/recordings/TestUserManager_Organizations.yaml
Adds some tests for code that wasn't covered, most uncovered code now is pieces that can't be setup to test (like deleting a grant for an account), or error cases within request logic.
=> Add some tests for uncovered code

CHANGELOG.md
Adds the changelog entry for 1.3.0
=> Add v1.3.0 changelog entry

CHANGELOG.md
Fixes the link for the 1.3.0 tag
=> Fix link to 1.3.0 tag

management/actions.go, management/blacklist.go, management/client.go, management/client_grant.go, management/connection.go, management/grant.go, management/hook.go, management/organization.go, management/resource_server.go, management/role.go, management/rule.go, management/rule_config.go, management/user.go, test/data/recordings/TestClientGrantManager_Organizations.yaml, test/data/recordings/TestOrganizationManager_ClientGrants.yaml, test/data/recordings/TestUserManager_AuthenticationMethods.yaml
Updates the doc strings for the List (and List related) functions to:
* Remove `all` to avoid indicating they do not need to be paginated
* Link to the pagination docs on pkg.go.dev
It also removes some usage of `applyListDefaults` that were added erroneously.
=> [SDK-4715] Update documentation to state List related functions should be paginated

authentication/authentication_request.go, authentication/authentication_test.go, authentication/oauth_test.go, internal/client/client_test.go, internal/idtokenvalidator/idtokenvalidator_test.go, management/management_test.go
There's a bunch of new errors being raised by golangci-lint coming from revive now adding support for checking function literals, this fixes all the lint errors that are being raised.
=> Fix lint errors from new golangci-lint

management/management.gen.go, management/management.gen_test.go, management/prompt.go, management/prompt_test.go, test/data/recordings/TestPromptManager_CreatePartials.yaml, test/data/recordings/TestPromptManager_DeletePartials.yaml, test/data/recordings/TestPromptManager_ReadPartials.yaml, test/data/recordings/TestPromptManager_UpdatePartials.yaml
This refactors, fixes and improves the implementation for prompt partials introduced in https://github.com/auth0/go-auth0/pull/341
- https://github.com/auth0/go-auth0/pull/341
=> Fix prompt partials

management/client.go, management/client_test.go, management/management.gen.go, management/management.gen_test.go, test/data/recordings/TestClient_CreateWithOIDCLogout.yaml
This PR adds support for the `oidc_logout` nested object available on the clients resource.
The old `oidc_backchannel_logout` struct was also deprecated in favour of the new `oidc_logout`. Make sure the new attribute is used going forward. 
- Docs: https://auth0.com/docs/api/management/v2/clients/post-clients
```json
"oidc_logout": {
"backchannel_logout_urls": [
"string"
],
"backchannel_logout_initiators": {
"mode": "custom",
"selected_initiators": [
"rp-logout"
]
}
}
```
=> [GH-373] Add support for oidc logout parameters

.github/workflows/e2e-tests.yml, .github/workflows/main.yml
=> Add Token for CodeCov Report

management/connection.go, management/connection_test.go, test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Attribute_required_in_profile_but_inactive_on_signup.yaml, test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Cannot_set_both_requires_username_and_attributes_together.yaml, test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Cannot_set_both_validation_and_attributes_together.yaml, test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_With_No_attribute_is_active.yaml, test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_With_RequireUsername.yaml, test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_Email_as_Identifier.yaml, test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_PhoneNumber_as_Identifier.yaml, test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_Username_as_Identifier.yaml
- Added `omitempty` on Boolean Structs of Auth0 Connection Options.
=> Fix Optional Fields on Auth0 Connection Options

EXAMPLES.md, management/client.go, management/client_test.go, management/management.gen.go, management/management.gen_test.go, management/resource_server.go, management/resource_server_test.go, management/tenant.go, management/tenant_test.go
- Fixed Naming Conventions For HRI Features Support
=> Fixed Naming Conventions For HRI Features Support

management/client.go, management/management.gen.go, management/management.gen_test.go
Added support for **Sign in With Google** for native apps in `ClientManager`.
- Introduced a new field in the `Client` struct:  
```go
Google *ClientNativeSocialLoginSupportEnabled `json:"google,omitempty"`
```
under `ClientNativeSocialLogin`.  
- This allows enabling or disabling Google Sign-In support for native apps.  
Below is an example of how to create and update a client with Google Sign-In enabled:
```go
package main
import (
"context"
"log"
"github.com/auth0/go-auth0/management"
"github.com/auth0/go-auth0"
)
func main() {
mgmt, err := management.New("your-domain", management.WithClientCredentials("your-client-id", "your-client-secret"))
if err != nil {
log.Fatal(err)
}
client := &management.Client{
Name:            auth0.String("My Client"),
CrossOriginAuth: auth0.Bool(true), …
```
=> Add Support For `Sign in With Google For Native Apps` in `ClientManager`

management/connection.go, management/connection_test.go, management/management.gen.go, management/management.gen_test.go, test/data/recordings/TestConnectionManager_Create/It_can_successfully_create_a_Wordpress_Connection.yaml, test/data/recordings/TestConnectionManager_Read/It_can_successfully_read_a_Wordpress_Connection.yaml, test/data/recordings/TestConnectionManager_ReadByName/It_can_successfully_find_a_Wordpress_Connection_by_its_name.yaml, test/data/recordings/TestConnectionManager_Update/It_can_successfully_update_a_Wordpress_Connection.yaml
- Added custom_headers attribute to ConnectionOptionsOAuth2 in ConnectionManager.
- Updated related test cases to cover the new attribute.
- Ensured backward compatibility and correctness.
- Verified that the new custom_headers attribute is correctly applied.
- Ran updated test cases to confirm expected behavior.
- Performed manual validation where required.
=> Add `custom_headers` Attribute to `ConnectionOptionsOAuth2` in `ConnectionManager`
