auth0/go-auth0

management/attack_protection.go
management/attack_protection_test.go
management/management.gen.go
management/management.go

In this PR we are adding support for the Attack Protection endpoints found at https://auth0.com/docs/api/management/v2#!/Attack_Protection/get_breached_password_detection. 
**Note**: The tests we are adding follow the style of all the other tests within this repo.

[DXCDT-44] Add attack protection endpoints

---

management/attack_protection.go

This fixes a small typo on the json tag for the allow list property. 
```json
"allowlist": [
"143.204.0.105",
"2600:9000:208f:ca00:d:f5f5:b40:93a1"
],
```

[DXCDT-61] Fix json tags on AllowList for Attack Protection structs

---

management/connection.go
management/management.gen.go

Add a new `show_as_button` option to be able to show a connection as a button.
Migrated from https://github.com/go-auth0/auth0/pull/257.

Add `ShowAsButton` option

---

management/user.go
management/user_test.go

The key `profileData` is present in social Identities (see below), but is not in the `UserIdentity` struct. This means that this SDK cannot be used to retrieve social profile data.
Here's an example of the key within an account with two identities:
```
...
"identities": [
{
"connection": "Initial-Connection",
"user_id": "123xyz",
"provider": "auth0",
"isSocial": false
},
{
"connection": "google-oauth2",
"user_id": "abc123",
"provider": "google-oauth2",
"isSocial": true,
"profileData": {
"family_name": "some name",
"picture": "https://cdn.googleusercontent.com/user/abc123"
}
}
],
...
```
This PR adds a `profileData` field to `UserIdentity` with type `*map[string]interface{}` so arbitrary schemas of social providers can be deserialized.
This PR was motivated by this thread on the community …

Add profileData key to UserIdentity

---

management/custom_domain.go
management/management.gen.go

When programmatically managing self-managed certificates, i.e. by requesting the `/verify` endpoint in code, the caller needs needs to know the values of the origin domain name and the `cname-api-key` header to set up the reverse proxy correctly. This change simply adds those two fields to the `CustomDomain` struct.
* auth0/terraform-provider-auth0#118

Add fields required to support self-managed certificates

---

management/user.go
management/user_test.go

adds a method to unlink a users identity
https://auth0.com/docs/api/management/v2#!/Users/delete_user_identity_by_user_id

add method to unlink a users identity

---

CHANGELOG.md
management/log_stream.go
management/log_stream_test.go

Add Filters to LogStream. 
https://auth0.com/docs/api/management/v2#!/Log_Streams/post_log_streams

[DXCDT-104] Add Filters to LogStream

---

management/email_template_test.go
management/email_test.go

Refactor email, email_template tests so they can be ran in any order and they clean up the test tenant after running.

[DXCDT-110] [DXCDT-113] Refactor email, email_template tests

---

management/management.gen.go
management/management.gen_test.go
management/prompt.go
management/prompt_test.go
management/testdata/recordings/TestPrompt.yaml

This PR adds support for the `webauthn_platform_first_factor_prompt` boolean flag in the prompt. This is required for proper support of it in the [Auth0 Terraform provider](https://github.com/auth0/terraform-provider-auth0/issues/102).
https://github.com/auth0/terraform-provider-auth0/issues/102

Add support for webauthn_platform_first_factor_prompt flag in the prompt

---

management/connection.go
management/management.gen.go
management/management.gen_test.go

As noted in [this Terraform provider issue](https://github.com/auth0/terraform-provider-auth0/issues/161), the `disableSignout` field is absent from SAMLP connection options, but is very much a real configuration. This PR adds this field in to then enable for the Terraform provider.
[Original issue](https://github.com/auth0/terraform-provider-auth0/issues/161)

Adding disable sign out field to SAMLP connection options

---

management/guardian.go
management/guardian_test.go
management/management.gen.go
management/management.gen_test.go
management/testdata/recordings/TestGuardian/MultiFactor/DUO/Enable.yaml
management/testdata/recordings/TestGuardian/MultiFactor/DUO/Settings.yaml

This PR adds support to update settings on Duo, needed for https://github.com/auth0/terraform-provider-auth0/issues/165.

[DXCDT-175] Add read and update to Duo Settings

---

management/connection.go
management/management.gen.go
management/management.gen_test.go

Adding the `pkce_enabled` field for OAuth2 connection options which controls the enablement of Proof Key for Code Exchange (PKCE).
- [Authorization Code Flow with Proof Key for Code Exchange (PKCE)](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce)
- [Original requesting Github issue](https://github.com/auth0/terraform-provider-auth0/issues/49)

Adding PKCE enablement field to OAuth2 connection options

---

management/management.gen.go
management/management.gen_test.go
management/tenant.go

Adding the following feature flags to the tenant resource:
- `allow_legacy_delegation_grant_types`
- `allow_legacy_ro_grant_types`
- `allow_legacy_tokeninfo_endpoint`
- `enable_legacy_profile`
- `enable_idtoken_api2`
- `no_disclose_enterprise_connections`
- `disable_management_api_sms_obfuscation`
- `enable_adfs_waad_email_verification`
- `revoke_refresh_token_grant`
- `dashboard_log_streams_next`
- `dashboard_insights_view`
- `disable_fields_map_fix`
These were all the [missing flags from the API docs](https://auth0.com/docs/api/management/v2#!/Tenants/patch_settings) plus an [additional requested feature flag](https://github.com/auth0/terraform-provider-auth0/issues/47).
This is not meant to be an exhaustive list of feature flags; there are several other feature flags that have varying …

Adding several missing tenant flags

---

management/management.gen.go
management/management.gen_test.go
management/tenant.go
management/tenant_test.go
management/testdata/recordings/TestTenantManager.yaml

Adding the `session_cookie` tenant property to enable the modification of session cookie behavior. This was originally requested in this [Terraform provider issue](https://github.com/auth0/terraform-provider-auth0/issues/55).  
This property is an object that contains a single `mode` property that accepts two string values: `"persistent"` and `"non-persistent"`.
- Original requesting issue: https://github.com/auth0/terraform-provider-auth0/issues/55
- [PATCH tenant settings endpoint documentation](https://auth0.com/docs/api/management/v2#!/Tenants/patch_settings)
Tested manually and also added test case to existing `TestTenantManager` test.

Add support for tenant `session_cookie` property

---

management/email_template.go
management/email_template_test.go
management/email_test.go
management/management.gen.go
management/management.gen_test.go
management/testdata/recordings/TestEmailManager_Delete.yaml
management/testdata/recordings/TestEmailManager_Read.yaml
management/testdata/recordings/TestEmailManager_Update.yaml
management/testdata/recordings/TestEmailTemplateManager_Create.yaml
management/testdata/recordings/TestEmailTemplateManager_Read.yaml
management/testdata/recordings/TestEmailTemplateManager_Replace.yaml
management/testdata/recordings/TestEmailTemplateManager_Update.yaml

This PR adds the `includeEmailInRedirect` boolean field for email templates. This comes per a [request in the Terraform provider](https://github.com/auth0/terraform-provider-auth0/issues/34).
**Additionally,** included are some minor testing changes to the email templates testing to improve assertions and repeatability. These testing changes are only somewhat related to the core change here, but somewhat messy to separate while ensuring testing on this feature; willing to separate if requested.
- [Update email templates endpoint documentation](https://auth0.com/docs/api/management/v2#!/Email_Templates/put_email_templates_by_templateName)
- [Original request](https://github.com/auth0/terraform-provider-auth0/issues/3)

Adding `IncludeEmailInRedirect` field for email templates

---

management/connection.go

Add more connection strategies that default to OAuth2.

[DXCDT-190] Add more connection strategies that default to OAuth2

---

management/management.go
management/management_test.go

This PR adds support for the `from` and `take` query params that Auth0 allows for cursor/checkpoint based pagination.
My organization needs this in order to build a more robust pagination solution that doesn't risk skipping items, and it is currently difficult to accomplish using the sdk.
This is the the only pagination query params not currently supported and it is [well documented by the official documentation](https://auth0.com/docs/api/management/v2/#!/Organizations/get_organizations).
This can be easily tested by just using the take and from functions before firing off a request to retrieve for example organizations.  I tested it myself with our own internal api, as well as added a small unit test.

Add support for checkpoint based pagination

---

internal/client/client.go
internal/client/client_test.go
management/management_option.go

In this PR we add  the ability to pass a custom audience when using client credentials. This is especially useful when using custom domains that are not publicly accessible.

Add ability to pass a custom audience when using client credentials

---

management/anomaly.go
management/branding.go
management/guardian.go
management/job.go
management/management_error.go
management/management_error_test.go
management/management_request.go
management/management_test.go
management/user.go

The push for these improvements originally starts from this issue: https://github.com/auth0/terraform-provider-auth0/issues/36, where under certain rare occasions we could get non HTML body in the responses and then throw an obscure error message, not really understanding what's happening. We try to make things a bit more obvious in this PR and increase the reliability of how we make http requests, there were also a couple of occasions when we didn't correctly close the response body. Further comments are provided in the code.

Enhance reliability of how we make requests and parse errors

---

management/actions.go
management/actions_test.go
management/client.go
management/client_grant.go
management/client_grant_test.go
management/connection.go
management/connection_test.go
management/example_test.go
management/hook.go
management/log_stream.go
management/log_stream_test.go
management/management.gen.go
management/management.gen_test.go
management/organization.go
management/organization_test.go
management/resource_server.go
management/resource_server_test.go
management/role_test.go
management/tenant.go
management/tenant_test.go
management/user_test.go

There are some fields that are unable to be explicitly set to empty when making requests. This occurs with fields that are tagged with `omitempty` in their struct definitions; the system has no way to differentiate between explicitly empty and omitted. This shortcoming has been frequently logged as an issue in the Terraform provider repo, cataloged [here](https://github.com/auth0/terraform-provider-auth0/issues/14). This PR attempts to completely rectify this inability by setting the field types to pointers. By doing so, we introduce a tertiary state that we can use to distinguish between omitted and explicitly empty values. 
⚠️ **Note:** These changes introduce breaking changes! However, the intention is for this to be one of the last breaking changes before v1.
- [Related issue in …

DXCDT-218: Allow empty fields through pointers 

---

management/connection.go

This PR adds the omitempty json tag so we prevent sending this field as "null" in case it is not set.
The API only accepts 2 values:
```json
{ "statusCode": 400, "error": "Bad Request", "message": "The identity_api property contains an invalid value. Valid values are 'azure-active-directory-v1.0', 'microsoft-identity-platform-v2.0'", "errorCode": "invalid_body" }
```
- https://github.com/auth0/terraform-provider-auth0/pull/361

DXCDT-232: Add omitempty to IdentityAPI on AzureAD options

---

management/branding_theme.go

Change types from int to float32 for increased precision on branding theme fields. 
- https://github.com/auth0/terraform-provider-auth0/issues/333

DXCDT-243: Improve precision of branding theme fields with float64 instead of int

---

management/branding_theme.go
management/branding_theme_test.go
management/testdata/recordings/TestBrandingThemeManager_Default.yaml

As requested in https://github.com/auth0/go-auth0/issues/110 we're adding the ability to retrieve the default branding theme.

DXCDT-250: Add ability to retrieve default branding theme

---

management/log.go
management/management.gen.go
management/management.gen_test.go

Need few more fields in the logs generated. The PR do the same. It add 2 new fileds to log struct 
1. User Name
2. Auth0 Org ID

Add missing fields in log struct

---

management/actions.go
management/actions_test.go
management/management.gen.go
management/management.gen_test.go
management/testdata/recordings/TestActionManager_LogSession.yaml

Adds support for creating a log session via the Management API for tailing Actions Logs.
Tested against a space with the following steps:
```go
package main
import (
"fmt"
"log"
_ "github.com/auth0/go-auth0"
"github.com/auth0/go-auth0/management"
)
func main() {
m, err := management.New(
"AUTH0_DOMAIN",
management.WithClientCredentials(
"AUTH0_CLIENT_ID",
"AUTH0_CLIENT_SECRET",
),
)
if err != nil {
log.Fatalf("failed to create client %v\n", err)
return
}
key := "action_id"
val := "ACTION_ID"
resp := &management.ActionLogSession{
Filters: []management.ActionLogSessionFilter{
{
Key: &key,
Val: &val,
},
},
}
err = m.Action.LogSession(resp)
if err != nil {
log.Fatalf("failed to create log session %v\n", err)
return
}
fmt.Printf("created log session URL: \n\nURL: %s\n", *resp.Url)
}
```
```js …
```

[DXEX-2581] Add support for Actions log sessions endpoint

---

management/email.go
management/email_provider.go
management/email_provider_test.go
management/email_test.go
management/management.gen.go
management/management.gen_test.go
management/management.go
management/testdata/recordings/TestEmailProviderManager_Create.yaml
management/testdata/recordings/TestEmailProviderManager_Delete.yaml
management/testdata/recordings/TestEmailProviderManager_Read.yaml
management/testdata/recordings/TestEmailProviderManager_Update.yaml

Support for email provider settings has been requested through https://github.com/auth0/terraform-provider-auth0/issues/384.
As we started adding this setting to the old `Email` struct, it was noted that the DX wasn't good enough to be able to distinguish between what settings and even what credentials are specific to each email provider.
To solve that we're introducing a brand new `EmailProvider` struct with specific credentials and settings for each email provider type. 
Also to avoid doing breaking changes we're just marking the old `Email` as deprecated and it will be removed in a future version.
- https://github.com/auth0/terraform-provider-auth0/issues/384
- https://github.com/auth0/terraform-provider-auth0/pull/393
- https://github.com/auth0/terraform-provider-auth0/pull/394

DXCDT-255: Add new email provider manager and deprecate old one

---

management/connection.go
management/connection_test.go
management/management.gen.go
management/management.gen_test.go
management/testdata/recordings/TestConnectionManager_Create/It_can_successfully_create_a_Okta_Connection.yaml
management/testdata/recordings/TestConnectionManager_Read/It_can_successfully_read_a_Okta_Connection.yaml
management/testdata/recordings/TestConnectionManager_ReadByName/It_can_successfully_find_a_Okta_Connection_by_its_name.yaml
management/testdata/recordings/TestConnectionManager_Update/It_can_successfully_update_a_Okta_Connection.yaml

This PR adds support for the Okta Workforce connection type.

DXCDT-256: Add support for Okta connection

---

management/guardian.go
management/guardian_test.go
management/testdata/recordings/TestGuardian/MultiFactor/Push/Provider.yaml

This PR adds the ability to retrieve the selected provider and update the provider for MultiFactor Push Notification settings.
This is needed because without properly selecting the provider to be sns, even if we update the custom app and sns settings, they won't take effect.

ESD-25022: Add Provider and UpdateProvider to MFA Push

---

management/log_stream.go
management/log_stream_test.go
management/management.gen.go
management/management.gen_test.go
management/testdata/recordings/TestLogStreamManager_Create/It_can_successfully_create_a_Mixpanel_LogStream.yaml
management/testdata/recordings/TestLogStreamManager_Delete/It_can_successfully_delete_a_Mixpanel_LogStream.yaml
management/testdata/recordings/TestLogStreamManager_Read/It_can_successfully_read_a_Mixpanel_LogStream.yaml
management/testdata/recordings/TestLogStreamManager_Update/It_can_successfully_update_a_Mixpanel_LogStream.yaml

* This adds a log stream type and sink for Mixpanel
* This does *not* include a recording for tests. I wasn't sure if adding one using my tenant and modifying the URL to use the go-auth0 tenant was appropriate.
Please let me know if I missed anything. Happy to add it. Would like this functionality to use with the Terraform provider.

Add Mixpanel log stream

---

management/log_stream.go
management/log_stream_test.go
management/management.gen.go
management/management.gen_test.go
management/testdata/recordings/TestLogStreamManager_Create/It_can_successfully_create_a_Segment_LogStream.yaml
management/testdata/recordings/TestLogStreamManager_Delete/It_can_successfully_delete_a_Segment_LogStream.yaml
management/testdata/recordings/TestLogStreamManager_Read/It_can_successfully_read_a_Segment_LogStream.yaml
management/testdata/recordings/TestLogStreamManager_Update/It_can_successfully_update_a_Segment_LogStream.yaml

This change adds a log stream type and sink for Segment.
Required in:
https://github.com/auth0/terraform-provider-auth0/pull/437
**NOTE**: I wrote the tests but was unable to run the test locally. Can you please run to make sure it works?

DXCDT-337: Add support for segment log stream

---

management/connection.go
management/management.gen.go
management/management.gen_test.go

Adding support for `enable_script_context` boolean parameter on the `options` block of an Auth0 DB Connection. Without it, users that have this enabled for their connection will constantly get `│ Error: 400 Bad Request: once enabled, options.enable_script_context can not be disabled` because the options property needs to be sent with all its values even on `PATCH` requests.
- https://github.com/auth0/terraform-provider-auth0/issues/410

DXCDT-350: Add EnableScriptContext to Connection Options

---

management/client.go

Initially raised in https://github.com/auth0/terraform-provider-auth0/issues/450, the `cross_origin_auth` json field is no longer in use within the Management API v2 (this can be verified within the api2 repo). It is replaced by `cross_origin_authentication` instead. To not introduce a breaking change for our users we'll keep the struct name as CrossOriginAuth and only focus on renaming the json tag.

DXCDT-352: Rename json tag cross_origin_auth to cross_origin_authentication

---

management/connection.go

While investigating https://github.com/auth0/terraform-provider-auth0/issues/455 it turns out we never actually correctly unmarshal the option types for ADFS connections, causing the terraform provider to not recognize `*management.ConnectionOptionsADFS`.
This will get tested through the terraform provider for now. We can follow up with tests on the go-auth0 SDK after we implement passing the metadata_xml through the field instead of getting it from a url.

DXCDT-353: Add missing switch case for adfs conn

---

management/connection.go
management/connection_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestConnectionManager_Create/It_can_successfully_create_a_ADFS_Connection.yaml
test/data/recordings/TestConnectionManager_Read/It_can_successfully_read_a_ADFS_Connection.yaml
test/data/recordings/TestConnectionManager_ReadByName/It_can_successfully_find_a_ADFS_Connection_by_its_name.yaml

In this PR we are adding a couple of missed options for the ADFS Connection type:
- FedMetadataXML
- Thumbprints
- SignInEndpoint
- TrustEmailVerified
- https://github.com/auth0/terraform-provider-auth0/issues/454
Tests are added as well.

DXCDT-354: Enhance ADFS Connection Options

---

Makefile

Pins the version of golangci-lint to a known working version rather than latest so that CI starts working again. I took this option rather than upgrading to go 1.20 to unblock the broken CI for the following reasons:
* Upgrading to go 1.20 and using latest golangci-lint causes some new issues when running `make lint`, these need reviewing and fixing
* go 1.20 isn't available on homebrew yet, so whilst possible to use it's not ideal to upgrade until that is available
Whether CI passes again, and I tested the relevant make commands work fine locally

Pin installed golangci-lint version

---

internal/client/client.go
internal/client/client_test.go
management/management.go
management/management_option.go
management/management_test.go

Introduces telemetry to the package which is being sent in the (new) `Auth0-Client` header.
By default the telemetry data sent is for the go-auth0 package however, it can be overridden by passing a custom Telemetry to the `WithTelemetry` function on `API.New`. The structure is as follows:
* name: A string that is name of the "thing" the telemetry data is for
* version: A string that is version of the "thing" the telemetry data is for
* env: A object of strings that is a grab-bag for any other data that the consumer of go-auth0 wishes to send, like OS version for example
By calling `WithNoTelemetry` the `Auth0-Client` header is not sent at all
I'm working on figuring out how to test this to make sure the data shows up as expected (rather than works in theory)

SDK-3949: Introduce sending client information with requests

---

.github/CODEOWNERS
opslevel.yml

Moves the codeowners and opslevel files over to represent DX SDKs as owners of the repo

Move codeowners and opslevel over to DX SDKs

---

.github/workflows/main.yml

We no longer need to run this in the lint workflow as it has its own dedicated workflow

Remove vulncheck step from lint workflow

---

Makefile
internal/client/client.go
internal/client/client_test.go
management/management_test.go

Adds the Go version being used into the `env` property of the `auth0-client` data. This will allow us to have some insight into the Go versions being used and ensure that our supported versions of Go reflect real usage.
I wasn't sure whether it's worthwhile removing the `go` prefix on the return value of `runtime.Version()` and figured it was probably safer to leave the value untouched.
Tested manually that the `env` property includes the correct data (see below for a snippet from the management logs of my tenant)
```json
"auth0_client": {
"name": "go-auth0",
"version": "latest",
"env": {
"go": "go1.20.1"
}
}
```

Add go version to env object on Auth0Client

---

management/connection.go
management/connection_test.go

allowed_audiences can be null, an empty string, or an array of strings. In order to handle this we have to implement a custom marshaller that will map to the expected value to avoid errors.
Fixes #14
Unit tests and tested setting the connection to have the listed values and using `Connection.List()` and `Connection.Read("<id>")` are able to return these values correctly

Handle difference in allowed_audiences field in GoogleOauth2 connection

---

management/connection.go
management/connection_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestConnectionManager_Create/It_can_successfully_create_a_Ping_Federate_Connection.yaml
test/data/recordings/TestConnectionManager_Read/It_can_successfully_read_a_Ping_Federate_Connection.yaml
test/data/recordings/TestConnectionManager_ReadByName/It_can_successfully_find_a_Ping_Federate_Connection_by_its_name.yaml

This adds support for the Ping Federate connection, it does not expose the `expires`, `subject`, or `thumbprints` properties as these are populated on creation/update by the backend based on the provided cert (which can be a string representing the contents of a pem file, or a base64 representation of the contents of a pem file).
In v1 we could potentially look into providing read-only properties such as these in a way that disallows a developer from overriding them.
terraform-provider-auth0/issues/428
Test creating and updating the properties of a Ping Federate connection locally alongside the unit tests added

Add support for Ping Federate connection

---

.golangci.yml
Makefile
internal/client/client.go
management/connection.go
management/connection_test.go
management/management.gen.go
management/management.gen_test.go
management/user.go
management/user_test.go
test/data/recordings/TestUserManager_AuthenticationMethods.yaml

Adds support for the following Factor Management endpoints
Method | Endpoint | Description
-- | -- | --
GET | [/api/v2/users/{user}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/get_authentication_methods) | Gets a list of authentication methods
GET | [/api/v2/users/{user}/authentication-methods/{authentication_method_id}](https://auth0.com/docs/api/management/v2#!/Users/get_authentication_methods_by_authentication_method_id) | Gets an authentication method by ID.
POST | [/api/v2/users/{id}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/post_authentication_methods) | Creates an authentication method for a given user.
PUT | [/api/v2/users/{user}/authentication-methods](https://auth0.com/docs/api/management/v2#!/Users/put_authentication_me …

[SDK-4015] Add Factor Management endpoints

---

management/connection.go
management/management.gen.go
management/management.gen_test.go

Adds support for the `disable_self_service_change_password` property on DB connections
terraform-provider-auth0/issues/486
Tested setting this on a connection in my tenant and it works as expected

Support setting disable_self_service_change_password on database connections

---

management/organization.go

Adds a note and link to #48 on the `Organization.Invitations` func to clarify how to paginate the response due to `totals` not being returned so `HasNext` does not work.
#48

Clarify how to correctly paginate organization invitations

---

.github/workflows/govulncheck.yml
management/hook.go

There is a compatibility issue between Templum/govulncheck-action and the latest govulncheck json format. This has been "fixed" for now in Templum/govulncheck-action by setting the default to a known working version, but by supplying `latest` we're overriding this fix. So for now don't set a govulncheck version
Additionally, this PR also fixes a lint warning from the newer version of golanci-lint about an unused parameter.
auth0/go-jwt-middleware/pull/196
This PR will fail too as we're using pull_request_target which runs the action based on the workflow defined in the base of this PR rather than from the PR, once merged it will pass

Remove vulncheck version in govulncheck workflow

---

management/log.go
management/log_test.go

This implements a custom `UnmarshalJSON` function for the `Log` type that will handle the differing types of `scope`. Although this is documented to be a `string` it appears in some instances (from checking, only `fsa` type events) to be an array of strings.
Unlike other instances where we have to implement this functionality, we do not need to implement a `MarshalJSON` function as we can only read the `Log` type, i.e. there is no create or update functionality exposed.
#189
Covered by unit tests

Handle instances where scope is returned as array in log entries

---

management/job.go
management/job_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestJobManager_VerifyEmail.yaml

This PR adds an optional `Identity` field to the `management.Job` struct, for use in the `(*JobManager).VerifyEmail` method.
Per the [docs](https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email), this field "must be provided to verify primary social, enterprise and passwordless email identities. Also, is needed to verify secondary identities.".
This field only accepts a subset of the `UserIdentity` fields, so I have implemented `(*Job).MarshalJSON` to allow the reuse of the `UserIdentity` struct whilst omitting the extraneous fields.
I have added the `Identity` parameter to `TestJobManager_VerifyEmail` and re-recorded the HTTP interactions, so this is covered by the end-to-end tests.

Support setting Identity and OrganizationID on VerifyEmail calls

---

management/client.go
management/management.gen.go
management/management.gen_test.go
management/tenant.go

Adds support for the `require_pushed_authorization_requests` client setting and tenant flag
Tested setting and retrieving Client and Tenant settings manually
- [] All new/changed/fixed functionality is covered by tests (or N/A)
- [] I have added documentation for all new/changed functionality (or N/A)

Support require_pushed_authorization_requests client setting and tenant flag

---

management/client.go
management/management.gen.go
management/management.gen_test.go

Add support for configuring the Back-Channel Logout URLs on a Client
Tested configuring manually as this feature is currently feature flagged.

Support configuring Back-Channel Logout URLs for a Client

---

management/gen-methods.go
management/management.gen.go
management/management.gen_test.go

Adds support for generating safe getters for `map[string]interface` types, this means that the SDK can generate a safe getter for all types used

[SDK-4235] Generate safe getters for map[string]interface types

---

MIGRATION_GUIDE.md
management/client.go
management/client_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestClient_CreateWithClientAddons.yaml

This improves the typing of the `Addons` property of a `Client` by moving the type from a simple `map[string]interface{}` to a struct that can include the dedicated settings.
There is not configuration for WS-FED that is stored in the `wsfed` object, it is instead set in the `Callbacks` and `ClientAliases`. Rather than include logic around this in the SDK (such as taking the properties and setting these), I chose to instead document this and leave this up to the user.
With this, we now only directly support 2 Addons, `SAML2` and `WS-FED`, which are the default supported Addons in new tenants. We will expand the supported Addons upon request.

[SDK-4223] Improve typing of Client Addons

---

management/client.go
management/client_test.go

This PR fixes an unmarshal issue with the UpdateCredential func, where after patching it, the client credential doesn't get the response unmarshalled into the credential var passed by reference.

Fix UpdateCredential func

---

MIGRATION_GUIDE.md
Makefile
internal/client/client.go
internal/client/client_test.go
management/log_test.go
management/management.go
management/management_option.go
management/management_test.go

This improves upon the existing retry logic implemented in the package by expanding the retry
conditions, allowing configuration of the retry conditions and allowing disabling retries.
By default the Management Client will retry a request 2 times, when there is a 429 status code
or if there is an error returned (except for a select couple of errors that are not recoverable). The `X-RateLimit-Reset` is consulted to ensure that the request will work, unless the time until the request is more than the maximum wait time.
The configuration of the max retries and status codes that will be retried on by providing a
`RetryOptions` struct with the required values with the `WithRetryOptions` function, and retries
can be disabled by passing the `WithNoRetries` function
The SDK will now retry a …

[SDK-4224] Allow configuration and disabling of retry strategy

---

authentication/authentication.go
authentication/authentication_error.go
authentication/authentication_error_test.go
authentication/authentication_option.go
authentication/authentication_request.go
authentication/authentication_test.go
authentication/database.go
authentication/database/database.go
authentication/database_test.go
authentication/http_recordings_test.go
authentication/oauth.go
authentication/oauth/oauth.go
authentication/oauth_test.go
go.mod
go.sum
internal/client/client_test.go
management/management_test.go
test/data/recordings/authentication/TestDatabaseSignUp.yaml
test/data/recordings/authentication/TestOAuthLoginWithPassword.yaml

Implements the initial base structure of the authentication client along with 2 methods in OAuth and Database in order to facilitate testing of JSON and form encoded requests.
This does not implement aspects such as ID token verification, telemetry and rate limiting onto the client which will be done in a future PR.
There is testing setup for these methods but currently it is dependent on tenant state (i.e. signed up users), randomising this data, recording management API interactions etc. proved difficult so I will file a ticket to ensure that this is dealt with as part of this effort. Current ideas are:
* Script that uses Auth0 CLI to set up required user
* Have a default user that will be stored for recordings and override this if running against a live tenant
Tested manually and …

[SDK-4231] Implement initial structure of auth client

---

management/client.go
management/management.gen.go
management/management.gen_test.go

Adds back support for all of the Client Addons listed in the [Management UI](https://auth0.com/docs/api/management/v2#!/Clients/get_clients_by_id), empty structs exist because the existence of the property is used to change behaviour
The structs were generated from the API directly.
https://auth0.com/docs/api/management/v2#!/Clients/get_clients_by_id

[SDK-4328] Add support for all Client Addons listed in Management API

---

authentication/authentication.go
authentication/oauth/oauth.go
authentication/passwordless.go
authentication/passwordless/passwordless.go
authentication/passwordless_test.go
test/data/recordings/authentication/TestLoginWithEmail.yaml
test/data/recordings/authentication/TestLoginWithSMS.yaml
test/data/recordings/authentication/TestSendEmail.yaml
test/data/recordings/authentication/TestSendSMS.yaml

This implements the passwordless APIs on the authentication client:
* SendEmail
* LoginWithEmail
* SendSMS
* LoginWithSMS
Covered by tests and test email manually. Currently testing SMS once I get twilio working

[SDK-4335] Add passwordless authentication APIs 

---

MIGRATION_GUIDE.md
management/management_option.go
management/management_test.go

Given that these referenced structs from the internal client package they were unusable externally.
So change the WithRetries to accept individual arguments that are then turned into a retry strategy
and remove the WithAuth0ClientInfo as in retrospect it isn't necessary and was superseded by the
WithAuth0ClientEnvEntry helper.

[SDK-4367] Don't use internal client structs as parameters

---

.github/workflows/e2e-tests.yml
.github/workflows/govulncheck.yml
.github/workflows/main.yml

This PR pins the `Templum/govulncheck-action`, `golangci/golangci-lint-action`, and `codecov/codecov-action` third-party actions to the full-length commit SHAs for their most recent releases.
Pinning an action to a full-length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository. [docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
Note: I've set the `beta` branch as the target for this PR merge to avoid creating complications during the eventual GA merge. Please adjust if you feel …

chore(security): Pin workflow actions to commit SHAs

---

authentication/authentication.go
authentication/authentication_option.go
authentication/authentication_test.go
internal/client/client.go
internal/client/client_test.go
management/management.go

By default the client information sent is for the go-auth0 package, it can be disabled using `WithNoAuth0ClientInfo` on an `authentication.New` call, and the `env` data can be added to by using the `WithAuth0ClientEnvEntry` on a `authentication.New`
Based on #164
Validated it shows in the manage logs

[SDK-4329] Introduce auth0client information into the authentication client

---

MIGRATION_GUIDE.md
management/connection.go

Removes the following connection strategies are they are no longer supported and will be rejected by the API if used.
- DigitalOcean
- Discord
- Figma
- Imgur
- Slack
- Spotify
- Twitch
- Vimeo

[SDK-4220] Remove no longer supported connection strategies

---

authentication/authentication.go
authentication/authentication_option.go
authentication/authentication_test.go

Exposes configuring the retry logic on the authentication client, similar to the management client, 
by default it will retry a request 2 times, when there is a 429 status code or if there is an error 
returned (except for a select couple of errors that are not recoverable). The X-RateLimit-Reset
is consulted to ensure that the request will work, unless the time until the request is more than 
the maximum wait time.
The configuration of the max retries and status codes that will be retried on by providing a
RetryOptions struct with the required values with the WithRetryOptions function, and retries
can be disabled by passing the WithNoRetries function
Based on #216

[SDK-4330] Add retry support and configuration to the authentication client

---

MIGRATION_GUIDE.md
management/client.go

These were incorrectly using snake case but they should be camel case. Have also validated the the other client addon properties against the API2 docs
auth0/terraform-provider-auth0/issues/757

Fix casing on SAML2ClientAddon properties

---

authentication/passwordless/passwordless.go

Improves the documentation on properties in the passwordless response and request structs. Properties that a developer should not set themselves (`Connection`, `GrantType`, and `Realm`) have not had docs added.

Add docs for passwordless request and response properties

---

management/connection.go
management/management.gen.go
management/management.gen_test.go

This PR is the v0 equivalent of #263, it adds all known properties to the `ad`, `adfs,` `pingfederate`, `saml`,  and `waad` connection options to prevent these options being removed when a update is performed
The diff here is slightly smaller as v1 introduced safe getters for `map[string]interface{}` and those are not included in this after being generated.

[SDK-4483] Add all known options to ad, adfs, pingfederate, saml, and waad (v0)

---

management/connection.go
management/management.gen.go
management/management.gen_test.go

Through https://github.com/auth0/go-auth0/pull/263/files we introduced the `ExtGroups` and `ExtProfile` properties on the `ConnectionOptionsPingFederate` and `ConnectionOptionsSAML`, however the scope tag was missed. This PR addresses that. 
To note also that unfortunately now we have inconsistent ways of describing the same attribute accepted by the API:
`ext_groups`
- `ConnectionOptionsPingFederate.ExtGroups`
- `ConnectionOptionsSAML.ExtGroups`
- `ConnectionOptionsAzureAD.Groups`
- `ConnectionOptionsGoogleApps.Groups`
`ext_profile`
- `ConnectionOptionsPingFederate.ExtProfile`
- `ConnectionOptionsSAML.ExtProfile`
- `ConnectionOptionsGoogleApps.ExtendedProfile`
- `ConnectionOptionsAzureAD.ExtendedProfile`

Add missing scope tags to connection options

---

management/connection.go

Fixes a typo on the json tag for `PreviousThumbprints` on the `ConnectionOptionsADFS` struct

Fix typo on adfs previousthumbrints json tag

---

management/connection.go

Adding a line strategy constant to be able to support it within https://github.com/auth0/terraform-provider-auth0/issues/785 as it's currently missing.

Add line connection strategy

---

management/connection.go

This fixes https://github.com/auth0/terraform-provider-auth0/issues/805, where we need to send either the `from` or `messaging_service_sid` as null in order to toggle them on or off. 
Note the payload when checking the network tab within the UI:
```
{
"options": {
"from": "+155",
"messaging_service_sid": null,
}
}
```

Remove omitempty from From and MessagingServiceSID on SMS Connection

---

management/connection.go

Add missing Scopes and SetScopes for PingFederate and SAML Connections and as well introducing a new ConnectionOptionsScoper to enforce the interface.

Add missing Scopes and SetScopes for PingFederate and SAML Connections

---

management/connection.go
management/management.gen.go
management/management.gen_test.go

Adding missed connection options for Google Workspace. 
- https://github.com/auth0/terraform-provider-auth0/issues/817

Add missing properties to GoogleApps conn

---

management/management.gen.go
management/management.gen_test.go
management/tenant.go

Adds support for the `allow_organization_name_in_authentication_api` tenant setting
auth0/terraform-provider-auth0/issues/826

Add support for the allow_organization_name_in_authentication_api tenant setting

---

management/management.gen.go
management/management.gen_test.go
management/tenant.go

Adds the `customize_mfa_in_postlogin_action` property to the tenant flags

[SDK-4644] Add CustomizeMFAInPostLoginAction tenant flag

---

management/connection.go
management/management.gen.go
management/management.gen_test.go
management/user.go

Adds passkey metadata to Connection and AuthenticationMethod structs

[SDK-4558] Add passkey metadata in authentication method and connections

---

CHANGELOG.md

Adds the changelog entry for v1.2.0

Add v1.2.0 changelog entry

---

README.md

Replace the usage of `context.Background` with `context.TODO` and add a comment recommending this should be replaced.
Ultimately, these represent the same value but this makes it clearer that they should be replaced and there should be an informed choice around what context is used.

Clarify context should be replaced based on application usage

---

management/connection.go
management/management.gen.go
management/management.gen_test.go

Adds support for `disable_self_service_change_password` on AD Connection Options.
- https://github.com/auth0/terraform-provider-auth0/issues/870

ESD-32354: Add disable_self_service_change_password to AD connection options

---

authentication/oauth.go
authentication/oauth/oauth.go
authentication/oauth_test.go
management/client_grant.go
management/client_grant_test.go
management/management.gen.go
management/management.gen_test.go
management/organization.go
management/organization_test.go
test/data/recordings/TestClientGrantManager_Organizations.yaml
test/data/recordings/TestOrganizationManager_ClientGrants.yaml
test/data/recordings/authentication/TestLoginWithClientCredentials/Should_support_passing_an_organization.yaml

Adds support for the functionality associated with Organizations and Client Grants
*  Passing an `organization` parameter when logging in with the Client Credentials grant
* Retrieving organizations associated with a client grant
* Associating and removing client grants with an organization, and retrieving client grants associated with an endpoint
Covered by unit tests and tested manually

Add support for using Organizations with Client Grants

---

authentication/doc.go
doc.go
management/doc.go

This PR splits the godoc into the separate packages rather than having both the auth and management client documentation in the top level.
Some screenshots of the docs below
<details>
<summary>Auth0 package page</summary>
</details>
<details>
<summary>Authentication package page</summary>
</details>
<details>
<summary>Manangement package page</summary>
</details>
If you want to view this locally then you can install godoc (`go install  golang.org/x/tools/cmd/godoc@latest`) and then run `godoc -http=:6060` in the repo. The documentation will be available on `http://localhost:6060/pkg/github.com/auth0/go-auth0/`
Fixes #305 alongside the refactor

Split godoc into separate packages

---

authentication/oauth.go
authentication/oauth/oauth.go
authentication/oauth_test.go
test/data/recordings/authentication/TestPushedAuthorizationRequest/Should_make_a_PAR_request.yaml
test/data/recordings/authentication/TestPushedAuthorizationRequest/Should_support_all_arguments.yaml

Add support for performing Pushed Authorization Requests using the authentication client provided
Covered by unit tests and tested manually

[SDK-4738] Add support for performing Pushed Authorization Requests

---

authentication/authentication_error.go
authentication/authentication_error_test.go
authentication/authentication_test.go
authentication/doc.go

Exports the `Error` type so that it can be used in type assertions and document this in the godoc for the authentication package.
Closes #315

Export an Authentication Error to allow type assertions

---

.github/workflows/e2e-tests.yml
.github/workflows/main.yml

Reverts auth0/go-auth0#376 due to breaking changes introduced in v4 requiring a token.

Revert "Bump codecov/codecov-action from 3.1.5 to 4.2.0"

---

management/organization.go
management/organization_test.go
test/data/recordings/TestOrganizationManager_Create.yaml

- Add support for enabled_connections field in CreateOrganization

[GH-366] - Add support for enabled_connections field in CreateOrganizationConnections

---

management/connection.go

- Refactor scopes schema and add Godoc documentation

[GH-398] Refactor scopes schema and add Godoc documentation

---

authentication/authentication_test.go
authentication/oauth_test.go
internal/idtokenvalidator/idtokenvalidator_test.go

Fix GolangCI-Lint warnings

---

management/management.gen.go
management/management.gen_test.go
management/organization.go
management/organization_test.go
test/data/recordings/TestOrganizationManager_Create.yaml
test/data/recordings/TestOrganizationManager_DBConnection.yaml
test/data/recordings/TestOrganizationManager_UpdateDBConnection/When_signup_and_assign_membership_are_false_should_succeed.yaml
test/data/recordings/TestOrganizationManager_UpdateDBConnection/When_signup_enabled_with_assign_membership_false_should_fail.yaml
test/data/recordings/TestOrganizationManager_UpdateDBConnection/When_signup_enabled_with_assign_membership_true_should_succeed.yaml

- Add is_signup_enabled field to OrganizationConnection

Add is_signup_enabled field to OrganizationConnection

---

management/resource_server.go
management/resource_server_test.go
test/data/recordings/TestResourceServer_Create.yaml
test/data/recordings/TestResourceServer_Delete.yaml
test/data/recordings/TestResourceServer_List.yaml
test/data/recordings/TestResourceServer_Read.yaml
test/data/recordings/TestResourceServer_TokenDialect/When_TokenDialect_is_access_token_authz_and_RBAC_enabled_should_succeed.yaml
test/data/recordings/TestResourceServer_TokenDialect/When_TokenDialect_is_access_token_should_succeed.yaml
test/data/recordings/TestResourceServer_TokenDialect/When_TokenDialect_is_rfc9068_profile_authz_and_RBAC_enabled_should_succeed.yaml
test/data/recordings/TestResourceServer_TokenDialect/When_TokenDialect_is_rfc9068_profile_should_succeed.yaml
test/data/recordings/TestResourceServer_Update.yaml

- docs: Update TokenDialect option details in go-auth0 documentation
- [Access Token Profiles](https://auth0.com/docs/secure/tokens/access-tokens/access-token-profiles)
- Updated tests to create and update the TokenDialect to ensure proper handling of the new documentation and functionality.

docs: Update TokenDialect option details in go-auth0 documentation

---

authentication/database/database.go
authentication/database_test.go
management/connection.go
management/connection_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Attribute_required_in_profile_but_inactive_on_signup.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Cannot_set_both_requires_username_and_attributes_together.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Cannot_set_both_validation_and_attributes_together.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_With_No_attribute_is_active.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_With_RequireUsername.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_Email_as_Identifier.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_PhoneNumber_as_Identifier.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_Username_as_Identifier.yaml
test/data/recordings/authentication/TestDatabaseSignUp_RequiresUsername.yaml
test/data/recordings/authentication/TestDatabaseSignUp_WithEmailIdentifier.yaml
test/data/recordings/authentication/TestDatabaseSignUp_WithPhoneNumberIdentifier.yaml
test/data/recordings/authentication/TestDatabaseSignUp_WithUsernameAndEmailIdentifiers.yaml
test/data/recordings/authentication/TestDatabaseSignUp_WithUsernameAndPhoneNumberIdentifiers.yaml
test/data/recordings/authentication/TestDatabaseSignUp_WithUsernameEmailAndPhoneNumberIdentifiers.yaml
test/data/recordings/authentication/TestDatabaseSignUp_WithUsernameIdentifier.yaml

- Added support for `attributes` and `precedence` fields to `ConnectionOptions` struct in the management package.
- Added `phone_number` field to `SignupRequest` struct in the authentication package to allow user signup with phone number.
- [Auth0 Management API: Create Connections](https://auth0.com/docs/api/management/v2/connections/post-connections)
- [Auth0 Authentication API: Signup](https://auth0.com/docs/api/authentication#signup)
The following test cases have been added to ensure the new functionality works as expected:
- **TestDatabaseSignUp_RequiresUsername**
- Tests the `Database.Signup` method with a connection that requires a username.
- **TestDatabaseSignUp_WithEmailIdentifier**
- Tests the `Database.Signup` method with a connection that requires an email.
- …

Add Support for `attributes` and `precedence` to ConnectionOptions & `phone_number` to SignupRequest Struct

---

management/management.gen.go
management/management.gen_test.go
management/management.go
management/self_service_profiles.go
management/self_service_profiles_test.go
management/ticket.go
test/data/recordings/TestSelfServiceProfileManager_Create.yaml
test/data/recordings/TestSelfServiceProfileManager_CreateTicket.yaml
test/data/recordings/TestSelfServiceProfileManager_Delete.yaml
test/data/recordings/TestSelfServiceProfileManager_List.yaml
test/data/recordings/TestSelfServiceProfileManager_Read.yaml
test/data/recordings/TestSelfServiceProfileManager_Update.yaml

Support for CRUD operations to the Self-Service Profile on Management APIs.
1. POST /api/v2/self-service-profiles
2. GET /api/v2/self-service-profiles
3. GET /api/v2/self-service-profiles/{id}
4. PATCH /api/v2/self-service-profiles/{id}
5. DELETE /api/v2/self-service-profiles/{id}
6. POST /api/v2/self-service-profiles/{id}/sso-ticket
[Create a self-service profile](https://sus.auth0.com/docs/api/management/v2/self-service-profiles/post-self-service-profiles)
[Retrieve self-service profiles](https://sus.auth0.com/docs/api/management/v2/self-service-profiles/get-self-service-profiles)
[Retrieve a self-service profile by id](https://sus.auth0.com/docs/api/management/v2/self-service-profiles/get-self-service-profiles-by-id)
[Update a self-service …

Add Support for Self Service Profiles

---

management/management.gen.go
management/management.gen_test.go
management/prompt.go
management/prompt_test.go
test/data/recordings/TestPromptManager_GetPartials.yaml
test/data/recordings/TestPromptManager_GetPartialsGuardGuardError.yaml
test/data/recordings/TestPromptManager_SetPartials.yaml
test/data/recordings/TestPromptManager_SetPartialsGuardGuardError.yaml

- Added new methods `GetPartials` and `SetPartials` for improved prompt partial management.
- The methods `ReadPartials`, `CreatePartials`, and `UpdatePartials` are deprecated. Use `GetPartials` and `SetPartials` instead.
- [Auth0 API: Get Partials](https://auth0.com/docs/api/management/v2/prompts/get-partials)
- [Auth0 API: Set Partials](https://auth0.com/docs/api/management/v2/prompts/put-partials)
- Verified `GetPartials` and `SetPartials` methods with new unit tests to ensure correct functionality.

Add support for new Prompts and Screens for Prompt Partial

---

.github/workflows/govulncheck.yml
.github/workflows/semgrep.yml

1. Changed `pull_request_target` to `pull_request` for improved security.
2. Removed the `authorize` job from the workflow.
3. Updated the workflow to remove dependencies on the `authorize` job by eliminating any `needs: authorize` lines.
4. Added a bypass for external pull requests, as this previously prevented users from merging PRs.

Changed pull_request_target to pull_request

---

.github/workflows/add-to-project.yml

- Adding add-to-project workflow for issues on go-auth0 repo

Adding add-to-project workflow for issues on go-auth0 repo

---

management/email_provider.go
management/email_provider_test.go
management/management.gen.go
management/management.gen_test.go

- Add support for `Custom` email provider in EmailProviderManager
- [Configure email provider](https://auth0.com/docs/api/management/v2/emails/post-provider)
- Performed manual testing to verify functionality.
- Added unit tests for JSON marshalling.
```go
emailProvider: &EmailProvider{
Name:               auth0.String("custom"),
Enabled:            auth0.Bool(true),
DefaultFromAddress: auth0.String("accounts@example.com"),
Credentials:        &EmailProviderCredentialsCustom{},
}
err := api.EmailProvider.Create(context.Background(), emailProvider)
if err != nil {
if err.(Error).Status() != http.StatusConflict {
t.Error(err)
}
}
```

Add support for `Custom` email provider in EmailProviderManager

---

management/prompt.go
management/prompt_test.go
test/data/recordings/TestPromptManager_ReadRendering.yaml
test/data/recordings/TestPromptManager_UpdateRendering.yaml
test/data/recordings/TestPromptManager_UpdateRenderingWithAdvancedMode.yaml
test/data/recordings/TestPromptManager_UpdateRenderingWithStandardMode.yaml

Update logic to handle the standardMode in PATCH API

---

management/connection.go
management/connection_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Attribute_required_in_profile_but_inactive_on_signup.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Cannot_set_both_requires_username_and_attributes_together.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_Cannot_set_both_validation_and_attributes_together.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_With_No_attribute_is_active.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_With_RequireUsername.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_Email_as_Identifier.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_Email_as_Identifier_With_VerificationMethod_Link.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_Email_as_Identifier_With_VerificationMethod_OTP.yaml
test/data/recordings/TestConnectionManager_CreateDBConnectionWithDifferentOptions/It_handles_Auth0_Connection_with_Username_as_Identifier.yaml

This pull request introduces support for the `VerificationMethod` attribute for email-based Auth0 `ConnectionOptions`. Two enums are included to represent the verification methods:
- `ConnectionOptionsEmailAttributeVerificationMethodLink`: Represents a verification method using a link.
- `ConnectionOptionsEmailAttributeVerificationMethodOtp`: Represents a verification method using an OTP (one-time password).
Additionally, test cases have been added to validate these changes.
- [Auth0 Management API: Create Connections](https://auth0.com/docs/api/management/v2/connections/post-connections)
- testcases have been added to validate the `VerificationMethod` attribute.
- Manual testing can be performed by configuring email-based connections with both `link` and `otp` verification methods and …

Add Support for `VerificationMethod` Attribute for Email-based Auth0 ConnectionOptions

---

management/management.gen.go
management/management.gen_test.go
management/management_request.go
management/management_test.go
management/user.go
management/user_test.go
test/data/recordings/TestUserManager_DeleteUserSessions.yaml
test/data/recordings/TestUserManager_ListUserSessions.yaml

This pull request adds support for user session endpoints in `UserManager` Specifically:
- **Added Methods:**
- `ListUserSessions`: Retrieves active sessions for a specific user.
- API Reference: [Get User Sessions](https://auth0.com/docs/api/management/v2/users/get-sessions-for-user)
- `DeleteUserSessions`: Deletes all active sessions for a specific user.
- API Reference: [Delete User Sessions](https://auth0.com/docs/api/management/v2/users/delete-sessions-for-user)
- These changes are important to manage user sessions programmatically and align with Auth0's Management API capabilities.
- [Get User Sessions API Documentation](https://auth0.com/docs/api/management/v2/users/get-sessions-for-user)
- [Delete User Sessions API Documentation](https://auth0.com/docs/api/management/v2/users/delet …

Add Support for User sessions Endpoints in `UserManager`

---

management/management.gen.go
management/management.gen_test.go
management/management.go
management/refresh_token.go
management/refresh_token_test.go
management/session.go
management/session_test.go
management/user.go
test/data/recordings/TestRefreshTokenManager_Delete.yaml
test/data/recordings/TestRefreshTokenManager_Read.yaml
test/data/recordings/TestSessionManager_Delete.yaml
test/data/recordings/TestSessionManager_Read.yaml
test/data/recordings/TestSessionManager_Revoke.yaml

- Added **RefreshTokenManager** with `read` and `delete` methods for managing refresh tokens.
- Added **SessionManager** with `read`, `delete`, and `revoke` methods for managing sessions.
- These additions provide more granular control over tokens and sessions via the Auth0 Management API.  
- [Auth0 Management API: Get a Session](https://auth0.com/docs/api/management/v2/sessions/get-session)  
- [Auth0 Management API: Delete a Session](https://auth0.com/docs/api/management/v2/sessions/delete-session)  
- [Auth0 Management API: Revoke a Session](https://auth0.com/docs/api/management/v2/sessions/revoke-session)  
- [Auth0 Management API: Get a Refresh Token](https://auth0.com/docs/api/management/v2/refresh-tokens/get-refresh-token)  
- [Auth0 Management API: Delete a Refresh …

Add Support for Refresh Tokens and Sessions Endpoints

---

management/branding_theme.go
management/branding_theme_test.go

- Added support for setting `captcha_widget_theme` in `BrandingTheme`.
- Introduced a new field in the `BrandingTheme` struct:
```go
CaptchaWidgetTheme string `json:"captcha_widget_theme"`
```
- This field has been added under `BrandingThemeColors` in `BrandingThemeManager`.
- Allows customization of the Captcha widget theme for branding.
- [Auth0 Branding API Documentation](https://auth0.com/docs/api/management/v2#!/Branding/patch_branding)]
- Ensure the `captcha_widget_theme` field is correctly serialized/deserialized in the `BrandingTheme` struct.
- Validate that updating the branding theme successfully applies the Captcha widget theme customization.

Add support for setting `captcha_widget_theme` in `BrandingTheme` Struct in `BrandingThemeManager`

---

management/prompt.go

- Add `customized-consent` to Prompt Allowlist For Prompt Partials in `PromptManager`

Add `customized-consent` to Prompt Allowlist For Prompt Partials in `PromptManager`

---

management/guardian.go
management/guardian_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestGuardian/MultiFactor/Push/DirectFCMv1.yaml

- Added support for the **FCM v1 endpoint**:  
[Auth0 Guardian API – Update FCMv1 Credentials](https://auth0.com/docs/api/management/v2/guardian/put-fcmv-1)
- Resolves #511  
-   [Auth0 Guardian API – Update FCMv1 Credentials](https://auth0.com/docs/api/management/v2/guardian/put-fcmv-1)
- Ran initial tests to verify changes  
- Added Test Recordings  
_First-time contributor—happy to make any modifications as needed!_ 😊

Add Support for `FCMv1 Server Credentials` in `MultiFactorPush` Sub-Manager of `GuardianManager`

---

authentication/authentication.go

To align with FAPI 2.0 and future client assertion requirements this changes the JWT Client Authentication assertion to use a single audience string value. The value itself is the issuer identifier.

refactor: use a single client assertion audience

---

management/user.go
management/user_test.go
test/data/recordings/TestUserManager_GetUserLogs.yaml

- Added `GetUserLogs` method in `UserManager` to fetch user log events.  
- [Auth0 Management API - Get User Logs](https://auth0.com/docs/api/management/v2/users/get-logs-by-user)
- Added test cases to validate the behavior of `GetUserLogs`.  
- Manually tested by calling the method with different user IDs and verifying log events returned match expectations.

Add support for `GetUserLogs` method to fetch user log events in `UserManager`

---

management/connection.go
management/connection_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestConnectionManager_Create/It_can_successfully_create_a_Wordpress_Connection.yaml
test/data/recordings/TestConnectionManager_Read/It_can_successfully_read_a_Wordpress_Connection.yaml
test/data/recordings/TestConnectionManager_ReadByName/It_can_successfully_find_a_Wordpress_Connection_by_its_name.yaml
test/data/recordings/TestConnectionManager_Update/It_can_successfully_update_a_Wordpress_Connection.yaml

This PR introduces a **breaking change** by updating the `CustomHeaders` field in `ConnectionOptionsOAuth2`:  
- **Changed `CustomHeaders` from `map[string]string` to `*[]map[string]string`** to support multiple headers with the same key.  
This change improves API compatibility and ensures headers are handled consistently.  
- Updated tests to validate the new `CustomHeaders` structure.

Breaking Change: Migrate `custom_headers` from `map[string]string` to `*[]map[string]string` in `ConnectionOptionsOAuth2`

---

management/client.go
management/client_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestClient_SessionTransfer.yaml

- Added support for the new `allow_refresh_token` field in the Session Transfer configuration.
This field has also been included in the existing test cases.
This feature was introduced in the latest version of Auth0.
Updated the existing test cases to cover the `allow_refresh_token` field.

Add `AllowRefreshToken` support to `SessionTransfer`  in `ClientManager`

---

management/custom_domain_test.go
management/management.gen.go
management/management.gen_test.go
management/prompt.go
management/prompt_test.go
test/data/recordings/TestBrandingManager_UniversalLogin.yaml
test/data/recordings/TestCustomDomainManager_Create.yaml
test/data/recordings/TestCustomDomainManager_Delete.yaml
test/data/recordings/TestCustomDomainManager_List.yaml
test/data/recordings/TestCustomDomainManager_Read.yaml
test/data/recordings/TestCustomDomainManager_Update.yaml
test/data/recordings/TestCustomDomainManager_Verify.yaml
test/data/recordings/TestPromptManager_CreatePartials.yaml
test/data/recordings/TestPromptManager_DeletePartials.yaml
test/data/recordings/TestPromptManager_GetPartials.yaml
test/data/recordings/TestPromptManager_ListRendering.yaml
test/data/recordings/TestPromptManager_ReadPartials.yaml
test/data/recordings/TestPromptManager_ReadRendering.yaml
test/data/recordings/TestPromptManager_UpdatePartials.yaml
test/data/recordings/TestPromptManager_UpdateRendering.yaml
test/data/recordings/TestPromptManager_UpdateRenderingWithAdvancedMode.yaml
test/data/recordings/TestPromptManager_UpdateRenderingWithStandardMode.yaml

This PR adds support for listing prompt rendering settings via the `PromptManager`. The following changes are included:
* Introduced `PromptRenderingList` struct to encapsulate multiple rendering settings.
* Implemented `ListRendering` method on `PromptManager` to retrieve all prompt rendering configurations.
* Added unit tests for `ListRendering` to validate expected behavior and response structure.
* Updated test recordings to reflect usage of temporary domain names, ensuring better test isolation and consistency.
* Adjusted existing test recordings across various managers to align with new domain setup.
* Added unit tests to validate the functionality of `ListRendering`.
* Verified end-to-end behavior through updated HTTP test recordings.
* Ensured consistency across test domains to …

Add Support for `ListRendering` method and associated tests for `PromptManager`

---

management/connection.go
management/connection_test.go
management/management.gen.go
management/management.gen_test.go
test/data/recordings/TestConnectionManager_EnabledClients.yaml
test/data/recordings/TestConnectionManager_UpdateEnabledClients_Add.yaml
test/data/recordings/TestConnectionManager_UpdateEnabledClients_Remove.yaml

* Added `ReadEnabledClients` and `UpdateEnabledClients` methods to manage clients enabled on a connection.
* Deprecated the `EnabledClients` field in the `Connection` struct in favor of these explicit methods.
Refer to:
* [Update enabled clients on a connection (PATCH)](https://auth0.com/docs/api/management/v2/connections/patch-clients)
* [Read enabled clients on a connection (GET)](https://auth0.com/docs/api/management/v2/connections/get-connection-clients)
* Auth0 Management API documentation on connection clients
* Created a client
* Created a connection
* Assigned the client to the connection using the new Go methods
* Verified the assignment in the Auth0 UI

Add `ReadEnabledClients` and `UpdateEnabledClients` methods; deprecate `EnabledClients` field in `Connection` struct of `ConnectionManager`

---

management/management_request.go
management/management_request_test.go

- Updated the `Body` request option in `management_request.go` to automatically set the `Content-Type: application/json` header when a body is provided.
- This ensures that when using `Body([]byte(...))`, the correct header is set without requiring the user to manually add a `Header` option.
- Fixes issues where requests using `Body` did not set the `Content-Type` header, leading to unexpected API errors.
- #561 
- Added/updated unit tests in `management_request_test.go` to verify that requests using the `Body` option now include the `Content-Type: application/json` header when a body is present.
- All existing and new tests pass, confirming correct header behavior for both payload and raw body scenarios.

Fix: Set Content-Type header to application/json for non-empty request bodies

---

management/client.go
management/management_request.go
management/management_request_test.go
management/prompt.go
management/token_exchange_profiles.go

* Re-enabled support for sending request bodies with HTTP `DELETE` requests.
* Added `nil` check before calling `CleanForPatch` in client update logic to prevent panics.
* Improved SDK robustness for flexible request handling.
* #564 
* Verified that DELETE requests with bodies are properly serialized and accepted.
* Covered Update logic with unit tests to ensure no panic occurs with a `nil` client.
* Manually tested client update scenarios with and without body content.

Revert `DELETE` body restriction and fix `CleanForPatch` nil checks in Update methods

---

management/resource_server.go

This PR updates the documentation comment for the `ResourceServerProofOfPossession` struct within the `ResourceServerManager`, clarifying support for the `dpop` (Demonstration of Proof-of-Possession) mechanism.
* Updated comment on the `Mechanism` field to include `"dpop"` as a valid option.
* Improves clarity and discoverability for developers implementing DPoP support via this SDK.
* Documentation-only change; no functional code was modified.
* No testing required.

docs: update comment to reflect DPoP support in `ResourceServerManager`

---

management/management.gen.go
management/management.gen_test.go
management/prompt.go
management/prompt_test.go
test/data/recordings/TestPromptManager_ListRendering.yaml
test/data/recordings/TestPromptManager_ReadRendering.yaml
test/data/recordings/TestPromptManager_UpdateRendering.yaml
test/data/recordings/TestPromptManager_UpdateRenderingWithAdvancedMode.yaml
test/data/recordings/TestPromptManager_UpdateRenderingWithStandardMode.yaml

* Added support for `Filters` in the `PromptRendering` struct to enable applying rendering rules conditionally based on client ID, connection, etc. This is represented as an optional `*PromptRenderingFilters` field.
* Introduced `UsePageTemplate` as an optional `*bool` field in `PromptRendering` to control whether the ACUL-based page template is used.
* Updated relevant Go SDK types to reflect these changes.
* Added test coverage for the new fields in rendering logic and JSON marshaling.
* Included documentation and usage comments for both fields.
* Supports ACUL configuration rendering enhancements
* Added unit tests to cover:
* JSON serialization/deserialization of `Filters` and `UsePageTemplate`
* Validation and conditional logic tied to these fields
* Verified compatibility with …

feat(prompt): add Filters and UsePageTemplate support to PromptRendering

---

management/guardian.go
management/guardian_test.go
test/data/recordings/TestGuardian/Enrollment/CreateTicket.yaml

Adding the fields missing from the guardian enrollment ticket mgmt API create ticket structure. Matching what is available in the mgmt API:
https://auth0.com/docs/api/management/v2/guardian/post-ticket
Example JSON:
```json
{
"user_id": "string",
"email": "user@example.com",
"send_mail": true,
"email_locale": "string",
"factor": "push-notification",
"allow_multiple_enrollments": true
}
```

fix: add missing mgmt api fields to guardian enrollment ticket structure
